<?php

namespace PG\ShortUrlBundle\Repository;

/**
 * Url
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Url extends \Doctrine\ORM\EntityRepository
{
}
